In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/diamonds.csv")

In [6]:
df

       carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [7]:
type(df)

pandas.DataFrame

In [8]:
#call top 5
df.head()

   carat diamond cut color clarity  depth  table  price     x     y     z
0   0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [9]:
#
df.head(10)

   carat diamond cut color clarity  depth  table  price     x     y     z
0   0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24   Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24   Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26   Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22        Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23   Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [12]:
#call last 10
df.tail(10)

       carat diamond cut color clarity  depth  table  price     x     y     z
53930   0.71     Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71     Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53932   0.70   Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70   Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53934   0.72     Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [13]:
#call a random sample n number of rows
df.sample()

       carat diamond cut color clarity  depth  table  price     x    y     z
49894    0.6   Very Good     E     VS1   63.2   56.0   2177  5.39  5.3  3.38

In [14]:
#overview of data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   carat        53940 non-null  float64
 1   diamond cut  53940 non-null  str
 2   color        53940 non-null  str
 3   clarity      53940 non-null  str
 4   depth        53940 non-null  float64
 5   table        53940 non-null  float64
 6   price        53940 non-null  int64
 7   x            53940 non-null  float64
 8   y            53940 non-null  float64
 9   z            53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.1 MB

In [15]:
#multiply carat series by 2
df.carat * 2

0        0.46
1        0.42
2        0.46
3        0.58
4        0.62
         ...
53935    1.44
53936    1.44
53937    1.40
53938    1.72
53939    1.50
Name: carat, Length: 53940, dtype: float64

In [16]:
#multiply df by 2 makes everything doubled (even the strings)
#calling color
df.color

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: str

In [19]:
#calling df.diamond cut won't work because there's a space. make sure to put camel case or something like it to avoid that

SyntaxError: invalid syntax (626455472.py, line 1)

In [20]:
#this will work though
df["diamond cut"]

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: diamond cut, Length: 53940, dtype: str

In [21]:
df.head()

   carat diamond cut color clarity  depth  table  price     x     y     z
0   0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [22]:
#what are the unique values of "diamond cut", also shows how many uniques there are
df["diamond cut"].unique()

<StringArray>
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Length: 5, dtype: str

In [23]:
#how many unique carat sizes are there?
df["diamond cut"].