# Calculating Across Rows

How do we calculate row-wise in Pandas like we do in Excel?

<img src="https://sandeepmj.github.io/image-host/oil-v-gold.png">

We need a couple of new concepts to do this calculation:

1. Capture a number from a cell and hold in variable.
2. We `apply()`calculations across columns, row-wise, using using a `lambda expression`.


This is step one in your ability to accomplish tasks that are highly specialized to your beats.

In [1]:
## import library
import pandas as pd

In [2]:
## pull in data
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/oil-v-gold-pandas.csv")
df

         Date  PX_GOLD  PX_OIL
0     1/31/08    922.7   91.75
1     2/29/08    975.0  101.84
2     3/31/08    916.2  101.58
3     4/30/08    865.1  113.46
4     5/30/08    887.3  127.35
..        ...      ...     ...
116   9/29/17   1281.5   51.67
117  10/31/17   1270.5   54.38
118  11/30/17   1273.2   57.40
119  12/29/17   1309.3   60.42
120   1/31/18   1339.0   64.73

[121 rows x 3 columns]

What are the different values for row **TWO** in this formula for `PX_GOLD`:

$$\text{Pct Chg at time } t = \frac{\text{Value at time } t - \text{Value at start time}}{\text{Value at start time}} \times 100$$

Use `.iat` to store a value from a specific cell into a variable:

```dataframe["column_name"].iat[row_index_number]```

In [ ]:
## hold gold
df["PX_GOLD"].iat[0]
float(df["PX_GOLD"].iat[0])

922.7

Also works:

`dataframe.iat[col_index_number, row_index_number]`

In [6]:
## hold gold col index, row index
df.iat[0,1]
gold_baseline = df.iat[0,1]
gold_baseline

np.float64(922.7)

Place the value for the starting oil price in a variable called `oil_baseline`

In [7]:
## oil_baseline
oil_baseline = df.iat[0,2]
oil_baseline

np.float64(91.75)

# `lambda expressions`

We're going to just write one first and then break it down:

In [19]:
## create a new column that holds the zero index for gold
df["gold_index"] = df["PX_GOLD"].apply(lambda x: ((x - gold_baseline) / gold_baseline) * 100)

df

,Date,PX_GOLD,PX_OIL,gold_index,oil_index,gold-100-index,oil-100-index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0,100.00
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7,111.00
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3,110.71
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8,123.66
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2,138.80
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9,56.32
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7,59.27
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0,62.56
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9,65.85
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1,70.55

## What  `x` stand for:

- In Pandas, we `apply()` lambda expressions to columns.
-  `.apply()`  works element-wise on each value in the `PX_GOLD` column, one at a time.
- `x` is a single value representing a cell in the column `PX_GOLD`
- The ```lambda x:``` processes each row of a dataframe, one row at a time.
-  The `lambda expression` takes each individual number `x` from `PX_GOLD` and runs the indexing formula on it.

Think of it as: "call each value in `PX_GOLD` as `x`, and do this math to using `x` in the formula."

## create a new column that holds the zero index for oil

In [20]:
## zero index oil

df["oil_index"] = df["PX_OIL"].apply(lambda x: ((x - oil_baseline) / oil_baseline) * 100)

In [21]:
## call df
df

,Date,PX_GOLD,PX_OIL,gold_index,oil_index,gold-100-index,oil-100-index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0,100.00
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7,111.00
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3,110.71
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8,123.66
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2,138.80
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9,56.32
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7,59.27
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0,62.56
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9,65.85
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1,70.55

### 100-indexing

Create cells below to add columns for both oil and gold for 100-indexing.

Reminder, the formula for 100-indexing:

$$\text{Index} = \left(\frac{\text{value at time } t}{\text{value at start}}\right) \times 100$$

In [25]:
## gold 100
df["gold-100-index"] = df["PX_GOLD"].apply(lambda x: round(x / gold_baseline * 100, 1))
df

,Date,PX_GOLD,PX_OIL,gold_index,oil_index,gold-100-index,oil-100-index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0,100.000000
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7,110.997275
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3,110.713896
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8,123.662125
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2,138.801090
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9,56.316076
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7,59.269755
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0,62.561308
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9,65.852861
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1,70.550409

In [24]:
## oil 100
df["oil-100-index"] = df["PX_OIL"].apply(lambda x: (x / oil_baseline * 100))
df

,Date,PX_GOLD,PX_OIL,gold_index,oil_index,gold-100-index,oil-100-index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0,100.000000
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7,110.997275
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3,110.713896
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8,123.662125
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2,138.801090
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9,56.316076
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7,59.269755
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0,62.561308
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9,65.852861
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1,70.550409

# Homework

<a href="https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv">This dataset</a> shows the price of a standard cable subscription and the U.S. median income annually between 1995-2023.

Has median income kept pace with the price of a cable subscription?

Round all numbers to 1 decimal place

In [19]:
## read file
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv")
df.head()

   year  avg_cable_bill  median_household_income
0  1995           22.35                    35249
1  1996           23.28                    36689
2  1997           26.31                    38229
3  1998           27.88                    40148
4  1999           28.94                    41994

In [20]:
## get info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     29 non-null     int64
 1   avg_cable_bill           29 non-null     float64
 2   median_household_income  29 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 828.0 bytes

### Index cable billl

In [21]:
## cable_baseline

cable_baseline = df["avg_cable_bill"].iat[0]
cable_baseline

np.float64(22.35)

In [22]:
df["cable_bill_index"] = df["avg_cable_bill"].apply(lambda x: round(((x-cable_baseline)/cable_baseline) * 100,1) )
df

    year  avg_cable_bill  median_household_income  cable_bill_index
0   1995           22.35                    35249               0.0
1   1996           23.28                    36689               4.2
2   1997           26.31                    38229              17.7
3   1998           27.88                    40148              24.7
4   1999           28.94                    41994              29.5
5   2000           31.22                    42349              39.7
6   2001           33.75                    42710              51.0
7   2002           36.47                    43057              63.2
8   2003           38.95                    43564              74.3
9   2004           41.04                    44684              83.6
10  2005           43.04                    46242              92.6
11  2006           43.26                    48451              93.6
12  2007           47.27                    50740             111.5
13  2008           49.65                    52029             122.1
14  2009           52.37                    50221             134.3
15  2010           54.44                    50046             143.6
16  2011           57.46                    50502             157.1
17  2012           61.63                    51371             175.7
18  2013           69.18                    52250             209.5
19  2014           71.45                    53657             219.7
20  2015           78.42                    55775             250.9
21  2016          150.98                    57617             575.5
22  2017          168.49                    61372             653.9
23  2018          199.99                    64324             794.8
24  2019          210.84                    69560             843.4
25  2020          217.42                    67521             872.8
26  2021          231.10                    70784             934.0
27  2022          251.48                    74580            1025.2
28  2023          291.81                    75143            1205.6

### Index median income

In [24]:
## income_baseline
income_baseline = df["median_household_income"].iat[0]
income_baseline

np.int64(35249)

In [25]:
df["income_index"] = df["median_household_income"].apply(lambda x: round(((x-income_baseline)/income_baseline) * 100,1) )
df

,year,avg_cable_bill,median_household_income,cable_bill_index,income_index
0,1995,22.35,35249,0.0,0.0
1,1996,23.28,36689,4.2,4.1
2,1997,26.31,38229,17.7,8.5
3,1998,27.88,40148,24.7,13.9
4,1999,28.94,41994,29.5,19.1
5,2000,31.22,42349,39.7,20.1
6,2001,33.75,42710,51.0,21.2
7,2002,36.47,43057,63.2,22.2
8,2003,38.95,43564,74.3,23.6
9,2004,41.04,44684,83.6,26.8
10,2005,43.04,46242,92.6,31.2
11,2006,43.26,48451,93.6,37.5
12,2007,47.27,50740,111.5,43.9
13,2008,49.65,52029,122.1,47.6
14,2009,52.37,50221,134.3,42.5
15,2010,54.44,50046,143.6,42.0
16,2011,57.46,50502,157.1,43.3
17,2012,61.63,51371,175.7,45.7
18,2013,69.18,52250,209.5,48.2
19,2014,71.45,53657,219.7,52.2
20,2015,78.42,55775,250.9,58.2
21,2016,150.98,57617,575.5,63.5
22,2017,168.49,61372,653.9,74.1
23,2018,199.99,64324,794.8,82.5
24,2019,210.84,69560,843.4,97.3
25,2020,217.42,67521,872.8,91.6
26,2021,231.10,70784,934.0,100.8
27,2022,251.48,74580,1025.2,111.6
28,2023,291.81,75143,1205.6,113.2

In [ ]:
## analysis
print("FINDINGS:")
print("The average cable bills rose more than ten times faster than household income between 1995 and 2023.")

FINDINGS:
The average cable bills rose more than ten times faster than household income between 1995 and 2023.