# Pivot & Calculating Z-Scores in Pandas


Recall that the Z-score tells you the precise numerical value of the standard deviation for an individual data point in your sample.

When you know the Z-score for two things that are measured in different ways, we know their "standard" scores which allows us to compare one against the other!

For example, we have a dataset of test scores for 100 students who have taken both both the ACT and SAT.
- The composite ACT had a mean score of 20.9 and SD of  6.
- The composite SAT had a mean score of 1060 and SD of 196.

**Create a column that tell us which score is better for each student.**

In [1]:
import pandas as pd
from IPython.display import display, HTML
## run the display code here
pd.options.display.float_format = '{:,.3f}'.format

## small trick to improve our display
## will allow us to see dataframes side-by-side
from IPython.display import display, HTML

css = """
.output {
    flex-direction: row;
}
"""

HTML('<style>{}</style>'.format(css))

In [2]:
## read standerized test score results data
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/standardized-test-scores.csv")
df

     student_ID  scores test
0             1      25  ACT
1             2      21  ACT
2             3      26  ACT
3             4      31  ACT
4             5      20  ACT
..          ...     ...  ...
195          96     767  SAT
196          97    1146  SAT
197          98    1139  SAT
198          99    1084  SAT
199         100    1032  SAT

[200 rows x 3 columns]

In [4]:
## let's confirm each student appears twice using query and sort
df.query("1 <= student_ID <= 10").sort_values(by = "student_ID")

     student_ID  scores test
0             1      25  ACT
100           1    1190  SAT
1             2      21  ACT
101           2    1053  SAT
2             3      26  ACT
102           3    1222  SAT
3             4      31  ACT
103           4    1411  SAT
4             5      20  ACT
104           5    1032  SAT
5             6      20  ACT
105           6    1032  SAT
6             7      31  ACT
106           7    1423  SAT
107           8    1248  SAT
7             8      26  ACT
108           9     981  SAT
8             9      19  ACT
9            10      25  ACT
109          10    1199  SAT

In [ ]:
## let's confirm each student appears twice using sort

In [11]:
## confirm our mean and STD to zero decimal places
# round(df[["act_scores", "sat_scores"]].agg(["mean", "std"]), 0)
round(df.groupby("test")["scores"].agg(["mean","std"]),1)

          mean     std
test
ACT     20.900   5.700
SAT  1,060.000 195.900

## Comparison challenge
Why is it difficult to compare the test scores for each student in the df's current shape?


<style>
    table {
        width: 100%;
        table-layout: fixed;
        border-collapse: collapse;
    }
    td {
        width: 50%;
        text-align: center;
        vertical-align: top;
        padding: 0;
    }
    img {
        max-width: 100%;
        height: auto;
        display: block;
        margin: 0;
        padding: 0;
    }
</style>
<table>
    <tr>
        <td><img src='https://sandeepmj.github.io/image-host/test-scores-tidy.png'></td>
        <td><img src='https://sandeepmj.github.io/image-host/test-scores-untidy.png'></td>
    </tr>
</table>

## Pivoting for comparison

We need to pivot our df so we can compare side by side the two types of test for each student.



```df.pivot(columns = "columns you want to pivot",
index = "What your new index should be",
values = "What values are for your columns"```

In [16]:
## pivot it.
dfp = df.pivot(columns = "test", index = "student_ID", values = "scores")
dfp

test        ACT   SAT
student_ID
1            25  1190
2            21  1053
3            26  1222
4            31  1411
5            20  1032
...         ...   ...
96           12   767
97           23  1146
98           23  1139
99           22  1084
100          20  1032

[100 rows x 2 columns]

In [17]:
## let's confirm both test scores appear for students 1-10
dfp.query(" 1 <= student_ID <= 10")

test        ACT   SAT
student_ID
1            25  1190
2            21  1053
3            26  1222
4            31  1411
5            20  1032
6            20  1032
7            31  1423
8            26  1248
9            19   981
10           25  1199

In [ ]:
## let's confirm both test scores appear 90-100

### Z-score or Standard score package

`from scipy.stats import zscore `

We target the `zscore` method on the column that must be standardized:

`zscore(df["target_col"])`

In [20]:
pip install scipy

Requirement already satisfied: scipy in /Users/gracet/miniforge3/envs/dataj-installs/lib/python3.11/site-packages (1.17.0)
Requirement already satisfied: numpy<2.7,>=1.26.4 in /Users/gracet/miniforge3/envs/dataj-installs/lib/python3.11/site-packages (from scipy) (2.4.2)
Note: you may need to restart the kernel to use updated packages.

In [21]:
## mad math functions package

from scipy.stats import zscore

In [23]:
# Calculate the SAT zscores and place in new zscores column
dfp["sat_zscore"] = zscore(dfp["SAT"])
dfp

test        ACT   SAT  sat_zscore
student_ID
1            25  1190       0.667
2            21  1053      -0.036
3            26  1222       0.831
4            31  1411       1.801
5            20  1032      -0.143
...         ...   ...         ...
96           12   767      -1.503
97           23  1146       0.441
98           23  1139       0.405
99           22  1084       0.123
100          20  1032      -0.143

[100 rows x 3 columns]

In [24]:
# Calculate the ACT zscores and place in new zscores column
dfp["act_zscore"] = zscore(dfp["ACT"])
dfp

test        ACT   SAT  sat_zscore  act_zscore
student_ID
1            25  1190       0.667       0.718
2            21  1053      -0.036       0.011
3            26  1222       0.831       0.895
4            31  1411       1.801       1.780
5            20  1032      -0.143      -0.166
...         ...   ...         ...         ...
96           12   767      -1.503      -1.582
97           23  1146       0.441       0.365
98           23  1139       0.405       0.365
99           22  1084       0.123       0.188
100          20  1032      -0.143      -0.166

[100 rows x 4 columns]

In [31]:
## create a column that says which test is stronger
dfp.apply(lambda row: "SAT" if row["sat_zscore"] > row["act_zscore"] else "ACT", axis = 1)
dfp

test        ACT   SAT  sat_zscore  act_zscore
student_ID
1            25  1190       0.667       0.718
2            21  1053      -0.036       0.011
3            26  1222       0.831       0.895
4            31  1411       1.801       1.780
5            20  1032      -0.143      -0.166
...         ...   ...         ...         ...
96           12   767      -1.503      -1.582
97           23  1146       0.441       0.365
98           23  1139       0.405       0.365
99           22  1084       0.123       0.188
100          20  1032      -0.143      -0.166

[100 rows x 4 columns]