# Sorting, Counting, Querying

We often have a large dataset but we are only interested in smaller sections of it.

Or we want to sort from largest to smallest.

Or perhaps we want to know how many instances of some value there is in the data.

Tonight we finally move beyond the basics to see the start of data analysis.

## Import libraries

In [ ]:
## import libraries

## Upload Olympics datasets to this notebook.

### Import ```olympics-summer.csv``` and store in a dataframe called ```dfs``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv">link</a>).


### Import ```olympics-winter.csv``` and store in a dataframe called ```dfw``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv">link</a>).

In [6]:
## import summer data
import pandas as pd
dfs = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv")
dfs.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN

In [8]:
dfs["Medal"].unique()

<StringArray>
[nan, 'Silver', 'Gold', 'Bronze']
Length: 4, dtype: str

In [33]:
## import winter data
dfw = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv")

## Get a sense of the data

In [13]:
#create dataframe for only summer games years and cities
dfw[["Year", "City", "Sport"]]

       Year      City                 Sport
0      1924  Chamonix            Ice Hockey
1      1924  Chamonix       Nordic Combined
2      1924  Chamonix           Ski Jumping
3      1924  Chamonix  Cross Country Skiing
4      1924  Chamonix       Nordic Combined
...     ...       ...                   ...
48559  2014     Sochi         Alpine Skiing
48560  2014     Sochi         Alpine Skiing
48561  2014     Sochi         Alpine Skiing
48562  2014     Sochi           Ski Jumping
48563  2014     Sochi           Ski Jumping

[48564 rows x 3 columns]

In [ ]:
## SUMMER
## what exactly do we have: columns, datatypes, etc.

In [ ]:
## WINTER
## what exactly do we have: columns, datatypes, etc.

## dataframe.sortvalues(by="Value 1", ascending = True) for A-Z or smaller numbers to bigger numbers

In [14]:
dfw.sort_values(by="City")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
20978,15276,Mario Brodmann,M,25.0,176.0,80.0,Switzerland,SUI,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
21994,57092,Axel Kammerer,M,27.0,181.0,88.0,Germany,GER,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
21993,57070,Jiro Kamiharako,M,25.0,176.0,64.0,Japan,JPN,1992,Albertville,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
21992,57070,Jiro Kamiharako,M,25.0,176.0,64.0,Japan,JPN,1992,Albertville,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
21991,57070,Jiro Kamiharako,M,25.0,176.0,64.0,Japan,JPN,1992,Albertville,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42206,93242,Lucia Peretti,F,19.0,163.0,50.0,Italy,ITA,2010,Vancouver,Short Track Speed Skating,"Short Track Speed Skating Women's 3,000 metres...",NaN
42207,93472,Rok Perko,M,24.0,186.0,93.0,Slovenia,SLO,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
42208,93479,Curdin Perl,M,25.0,181.0,74.0,Switzerland,SUI,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN
42202,93098,Paul Constantin Pepene,M,21.0,174.0,68.0,Romania,ROU,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 30 km Skiathlon,NaN
40102,33650,Vesna Fabjan,F,24.0,170.0,62.0,Slovenia,SLO,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Women's Team Sprint,NaN

In [15]:
#sort city z-a
dfw.sort_values(by="City", ascending=False)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
39561,11951,Ole Einar Bjrndalen,M,36.0,178.0,65.0,Norway,NOR,2010,Vancouver,Biathlon,Biathlon Men's 4 x 7.5 kilometres Relay,Gold
40747,52463,Marc Iselin,M,29.0,178.0,83.0,Switzerland,SUI,2010,Vancouver,Snowboarding,Snowboarding Men's Parallel Giant Slalom,NaN
40741,52316,Dmitry Gennadyevich Ipatov,M,25.0,176.0,60.0,Russia,RUS,2010,Vancouver,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
40742,52345,"Michael James Grant ""Mike"" Ireland",M,36.0,181.0,79.0,Canada,CAN,2010,Vancouver,Speed Skating,Speed Skating Men's 500 metres,NaN
40743,52392,Haley Lyn Irwin,F,21.0,170.0,78.0,Canada,CAN,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22495,75068,Dennis Edward Marineau,M,29.0,172.0,81.0,Canada-2,CAN,1992,Albertville,Bobsleigh,Bobsleigh Men's Two,NaN
22494,74979,Diego Margozzini,M,21.0,182.0,76.0,Chile,CHI,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
22493,74960,Pascal Margerit,M,20.0,180.0,75.0,France,FRA,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
22492,74931,Alexander Marent,M,22.0,168.0,68.0,Austria,AUT,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
21917,53932,Pawe Julian Jaroszek,M,20.0,185.0,82.0,Poland,POL,1992,Albertville,Speed Skating,"Speed Skating Men's 1,500 metres",NaN

In [18]:
dfw.sort_values(by=["City", "Year"])

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
20579,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
20580,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
20581,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
20582,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
20583,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43668,135492,Veronika Zuzulov (-Velez),F,25.0,172.0,72.0,Slovakia,SVK,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Giant Slalom,NaN
43669,135492,Veronika Zuzulov (-Velez),F,25.0,172.0,72.0,Slovakia,SVK,2010,Vancouver,Alpine Skiing,Alpine Skiing Women's Slalom,NaN
43670,135496,Veronika Zvaiov,F,21.0,176.0,62.0,Czech Republic,CZE,2010,Vancouver,Biathlon,Biathlon Women's 7.5 kilometres Sprint,NaN
43671,135500,Kristaps Zvejnieks,M,17.0,185.0,87.0,Latvia,LAT,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
43672,135500,Kristaps Zvejnieks,M,17.0,185.0,87.0,Latvia,LAT,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Slalom,NaN

In [19]:
#in summer dataframe, add "season" column with value "summer"
dfs["Season"] = "summer"
dfs.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer

In [21]:
dfw["Season"]="winter"
dfw.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter

In [22]:
#1 equal sign is an assignment
x = 10
x

10

In [23]:
#2 equal signs check for equality
x == 12

False

In [24]:
dfw.columns

Index(['ID', 'Athlete Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC',
       'Year', 'City', 'Sport', 'Event', 'Medal', 'Season'],
      dtype='str')

In [28]:
#are the 2 column headers identical?
dfw.columns == dfs.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [71]:
#ignore the below, it led to the wrong total index
#df = pd.concat([dfs,dfw])
df = pd.concat([dfs,dfw], ignore_index = True)
df
#print(df.query("Year == 1900").head())
#print("1900 rows:", (df["Year"] == 1900).sum())

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,NaN
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,NaN
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,NaN
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,NaN
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,NaN

In [72]:
#return df that only holds Sochi data: df.query("ColumnName == 'some_value'")
df.query("City == 'Sochi'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
266225,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,NaN
266226,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,NaN
266227,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,NaN
266228,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,NaN
266229,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,NaN
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,NaN
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,NaN
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,NaN
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,NaN

In [73]:
df.query("Year == 2000")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
155078,12,Jyri Tapani Aalto,M,31.0,172.0,70.0,Finland,FIN,2000,Sydney,Badminton,Badminton Men's Singles,NaN,summer
155079,13,Minna Maarit Aalto,F,34.0,159.0,55.5,Finland,FIN,2000,Sydney,Sailing,Sailing Women's Windsurfer,NaN,summer
155080,18,Timo Antero Aaltonen,M,31.0,189.0,130.0,Finland,FIN,2000,Sydney,Athletics,Athletics Men's Shot Put,NaN,summer
155081,23,Fritz Aanes,M,22.0,187.0,89.0,Norway,NOR,2000,Sydney,Wrestling,"Wrestling Men's Light-Heavyweight, Greco-Roman",NaN,summer
155082,30,Pepijn Aardewijn,M,30.0,189.0,72.0,Netherlands,NED,2000,Sydney,Rowing,Rowing Men's Lightweight Double Sculls,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168894,135522,"Klaas Erik ""Klaas-Erik"" Zwering",M,19.0,189.0,80.0,Netherlands,NED,2000,Sydney,Swimming,Swimming Men's 200 metres Backstroke,NaN,summer
168895,135522,"Klaas Erik ""Klaas-Erik"" Zwering",M,19.0,189.0,80.0,Netherlands,NED,2000,Sydney,Swimming,Swimming Men's 4 x 100 metres Medley Relay,NaN,summer
168896,135563,Olesya Nikolayevna Zykina,F,19.0,171.0,64.0,Russia,RUS,2000,Sydney,Athletics,Athletics Women's 4 x 400 metres Relay,Bronze,summer
168897,135565,Fernando scar Zylberberg,M,23.0,168.0,76.0,Argentina,ARG,2000,Sydney,Hockey,Hockey Men's Hockey,NaN,summer
168898,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,summer

In [74]:
#only use the `` for columns 
df.query("`Athlete Name` == 'Forough Abbasi'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
266226,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,NaN

In [75]:
#find all 1900 competitions
df.query("Year == 1900")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
380,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,summer
381,133,Franz Abb,M,NaN,NaN,NaN,Germany,GER,1900,Paris,Gymnastics,Gymnastics Men's Individual All-Around,NaN,summer
382,150,Margaret Ives Abbott (-Dunne),F,23.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,Gold,summer
383,151,Mary Perkins Ives Abbott (Perkins-),F,42.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,NaN,summer
384,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,131733,William Hayden Wright,M,NaN,NaN,NaN,A North American Team,USA,1900,Paris,Polo,Polo Men's Polo,Bronze,summer
2312,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's Foil, Masters, Individual",NaN,summer
2313,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's epee, Masters, Individual",NaN,summer
2314,133807,Pyotr Antonovich Zakovorot,M,NaN,NaN,NaN,Russia,RUS,1900,Paris,Fencing,"Fencing Men's Sabre, Masters, Individual",NaN,summer
2315,134198,"Walter John ""Jack"" Zealley",M,NaN,NaN,NaN,Upton Park FC,GBR,1900,Paris,Football,Football Men's Football,Gold,summer

In [77]:
df.query("1940 <= Year <= 1960")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
36483,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze,summer
36484,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Team All-Around,Gold,summer
36485,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Floor Exercise,NaN,summer
36486,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Horse Vault,Gold,summer
36487,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Parallel Bars,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229422,134268,Kazimierz Zelek,M,22.0,169.0,64.0,Poland,POL,1960,Squaw Valley,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN,NaN
229423,134875,Nina Alekseyevna Zhuk (Bakusheva-),F,25.0,NaN,NaN,Soviet Union-1,URS,1960,Squaw Valley,Figure Skating,Figure Skating Mixed Pairs,NaN,NaN
229424,134876,Stanislav Alekseyevich Zhuk,M,25.0,NaN,NaN,Soviet Union-1,URS,1960,Squaw Valley,Figure Skating,Figure Skating Mixed Pairs,NaN,NaN
229425,135022,Josef Egon Norbert Zimmermann,M,27.0,NaN,NaN,Austria,AUT,1960,Squaw Valley,Alpine Skiing,Alpine Skiing Men's Downhill,NaN,NaN
229426,135376,Ross Barta Zucco,M,25.0,NaN,NaN,United States,USA,1960,Squaw Valley,Speed Skating,"Speed Skating Men's 10,000 metres",NaN,NaN

In [76]:
df.query("Year == 1936 & NOC == 'USA'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
30008,762,"Gordon Belgum ""Gordy"" Adam",M,21.0,NaN,NaN,United States,USA,1936,Berlin,Rowing,Rowing Men's Coxed Eights,Gold,summer
30012,829,"Morgan Orlando Adams, Jr.",M,20.0,NaN,NaN,Mystery,USA,1936,Berlin,Sailing,Sailing Mixed 6 metres,NaN,summer
30036,1339,William Alexander (Wilhelm Alexander-) Ahlemeyer,M,29.0,NaN,NaN,United States,USA,1936,Berlin,Handball,Handball Men's Handball,NaN,summer
30054,2387,"David Donald ""Dave"" Albritton",M,23.0,191.0,79.0,United States,USA,1936,Berlin,Athletics,Athletics Men's High Jump,Silver,summer
30063,2552,Hugh Vincenzo Alessandroni,M,28.0,NaN,NaN,United States,USA,1936,Berlin,Fencing,"Fencing Men's Foil, Individual",NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224784,128832,"Alan Morgan ""Al"" Washbond",M,36.0,NaN,NaN,United States-1,USA,1936,Garmisch-Partenkirchen,Bobsleigh,Bobsleigh Men's Two,Gold,NaN
224785,128834,"Albert Lincoln ""Link"" Washburn",M,24.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Alpine Skiing,Alpine Skiing Men's Combined,NaN,NaN
224793,129326,Estelle D. Weigel (-Schmitt),F,21.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Figure Skating,Figure Skating Women's Singles,NaN,NaN
224794,129328,Louise E. Weigel (-Atwill),F,23.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Figure Skating,Figure Skating Women's Singles,NaN,NaN
224814,131578,"Elizabeth Davenport ""Betty"" Woolsey",F,27.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Alpine Skiing,Alpine Skiing Women's Combined,NaN,NaN

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  str
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   str
 13  Season        222552 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 29.0 MB

In [79]:
india_df = df.query("NOC == 'IND'")
india_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
1824,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 60 metres,NaN,summer
1825,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 100 metres,NaN,summer
1826,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres,Silver,summer
1827,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
1828,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres Hurdles,Silver,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263565,58899,Shiva Keshavan,M,28.0,183.0,85.0,India,IND,2010,Vancouver,Luge,Luge Men's Singles,NaN,NaN
264127,72364,Tashi Lundup,M,25.0,175.0,74.0,India,IND,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN,NaN
264481,84450,Jamyang Namgial,M,24.0,170.0,71.0,India,IND,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,NaN
267971,52325,Nadeem Iqbal,M,30.0,173.0,65.0,India,IND,2014,Sochi,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN,NaN
270515,119471,Himanshu Thakur,M,20.0,167.0,54.0,India,IND,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,NaN

In [80]:
india=df.query("Medal =='Gold' or Medal == 'Silver' or Medal == 'Bronze'").sort_values(by = "Medal")
india_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
1824,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 60 metres,NaN,summer
1825,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 100 metres,NaN,summer
1826,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres,Silver,summer
1827,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
1828,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres Hurdles,Silver,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263565,58899,Shiva Keshavan,M,28.0,183.0,85.0,India,IND,2010,Vancouver,Luge,Luge Men's Singles,NaN,NaN
264127,72364,Tashi Lundup,M,25.0,175.0,74.0,India,IND,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN,NaN
264481,84450,Jamyang Namgial,M,24.0,170.0,71.0,India,IND,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,NaN
267971,52325,Nadeem Iqbal,M,30.0,173.0,65.0,India,IND,2014,Sochi,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN,NaN
270515,119471,Himanshu Thakur,M,20.0,167.0,54.0,India,IND,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,NaN

## create more cells as necessary

In [90]:
## bring in our diamonds dataset
diamonds_df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/diamonds.csv")
diamonds_df

       carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [96]:
# number of unique cuts
diamonds_df["diamond cut"].nunique()

5

In [101]:
diamonds_df["diamond cut"].value_counts(ascending = True).to_frame("Quantity")
#to_frame makes the pretty table

             Quantity
diamond cut
Fair             1610
Good             4906
Very Good       12082
Premium         13791
Ideal           21551

In [102]:
#normalize gives in percent of total. by default, info is given as normalize = False
diamonds_df["diamond cut"].value_counts(normalize = True)

diamond cut
Ideal        0.399537
Premium      0.255673
Very Good    0.223990
Good         0.090953
Fair         0.029848
Name: proportion, dtype: float64

In [106]:
#round it
round(diamonds_df["diamond cut"].value_counts(normalize = True) * 100, 2)

diamond cut
Ideal        39.95
Premium      25.57
Very Good    22.40
Good          9.10
Fair          2.98
Name: proportion, dtype: float64